# Generated by Django 3.2.5 on 2022-05-28 15:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tripname', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('vehicle', models.CharField(blank=True, max_length=100, null=True)),
                ('startDate', models.DateField(blank=True, null=True)),
                ('endDate', models.DateField(blank=True, null=True)),
                ('attractions', models.JSONField(blank=True, null=True)),
                ('travel_time', models.JSONField(blank=True, null=True)),
                ('notes', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(blank=True, default='ongoing', max_length=10)),
                ('host', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
