# Generated by Django 3.2.5 on 2022-05-25 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerary',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
