# Generated by Django 3.2.5 on 2022-05-29 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0002_auto_20220529_1913'),
        ('itinerary', '0002_auto_20220529_2059'),
    ]

    operations = [
    ]
