# Generated by Django 3.2.5 on 2022-05-26 15:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0002_alter_itinerary_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itinerary',
            name='title',
        ),
        migrations.AddField(
            model_name='itinerary',
            name='attractions',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='notes',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='travel_time',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='trip_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='vehicle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
