# Generated by Django 3.2.5 on 2022-05-26 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0003_auto_20220526_2300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itinerary',
            old_name='trip_name',
            new_name='title',
        ),
    ]
