# Generated by Django 3.2.5 on 2022-05-26 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0004_rename_trip_name_itinerary_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itinerary',
            old_name='end_date',
            new_name='endDate',
        ),
        migrations.RenameField(
            model_name='itinerary',
            old_name='start_date',
            new_name='startDate',
        ),
    ]
