# Generated by Django 3.2.5 on 2022-05-26 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0005_auto_20220526_2322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itinerary',
            old_name='location',
            new_name='area',
        ),
    ]
