# Generated by Django 3.2.5 on 2022-05-28 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0007_auto_20220527_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerary',
            name='endDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='startDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
