# Generated by Django 3.2.5 on 2022-05-27 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0008_alter_itinerary_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='host',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
