# Generated by Django 3.2.5 on 2022-05-28 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0008_auto_20220528_0603'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itinerary',
            old_name='area',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='itinerary',
            old_name='title',
            new_name='tripname',
        ),
    ]
